import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Inter } from 'next/font/google';

import './globals.css';

import Footer from '@/components/footer';
import Loading from './loading';
import Navbar from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" type="image/*" sizes="any" />
      </head>
      <body className={inter.className}>
        <div className="max-w-screen-xl mx-auto bg-[#0F1117]">
          <Navbar />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Footer />
        </div>
      </body>
    </html>
  );
}
